name: Build AlgorithmAdventure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Step 3: Restore NuGet packages (if needed)
    - name: Restore NuGet packages
      run: nuget restore AlgorithmAdventure.sln

    # Step 4: Build the solution with Release|x64
    - name: Build the solution
      run: msbuild AlgorithmAdventure.sln /p:Configuration=Release /p:Platform=x64
