name: Build C++ Solution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3.0.0

    - name: Build solution
      run: msbuild AlgorithmAdventure.sln /p:Configuration=Release
